quarkus:
  http:
    port: 8083
    datasource:
      db-king: postgresql
      username: myuser
      password: mypassword
      jdbc:
        url: jdbc:postgresql://localhost:5432/mydatabase
        max-size: 16